### ISSUE TITLE
HYDRA_TOPO_DEBUG does not show bindset despite using bind-to option

### ISSUE THREAD

**Issue by KavithaTipturMadhu** [pmodels/mpich#3361]
`HYDRA_TOPO_DEBUG=1` does not show process bindset with `bind-to` option on KNL nodes. I checked this on KNL and Skylake nodes on JLSE. Turns out this the case in both the machines, and it looks like the `getenv` returns NULL when looking for `HYDRA_TOPO_DEBUG` on both of them. I set the environment manually using `setenv` in `HYDT_topo_init` function and it works then.

**Comment by raffenet** [comment]
To expand, it seems that environment inheritance is not working as expected on JLSE nodes. MPI processes should inherit environment settings (envvars, ulimit, etc.) from `mpiexec`.

**Comment by KavithaTipturMadhu** [comment]
@hzhou Some context if it helps debug: I checked this on KNL and Skylake nodes on JLSE. Turns out this the case in both the machines, and it looks like the `getenv` returns NULL when looking for `HYDRA_TOPO_DEBUG` on both of them. I set the environment manually using `setenv` in `HYDT_topo_init` function and it works then.  As far as I noticed, pmip.c isn't inheriting the environment variables of mpiexec.

**Comment by hzhou** [comment]
mpiexec.hydra invokes proxies passing all the env variables via command line: --global-inherited-env #count "A=.." "B=.." .... These variables are copied into environment of commands when proxy launches them; however, they are not necessary in proxy itself's environment -- especially when the proxy is launched through cobalt or manual mode.

**Comment by raffenet** [comment]
Is this fixed now that https://github.com/pmodels/mpich/pull/3432 is merged?

**Comment by KavithaTipturMadhu** [comment]
I'll check this once on KNL and confirm.

**Comment by KavithaTipturMadhu** [comment]
I still see nothing with HYDRA_TOPO_DEBUG=1 in jlse's KNL nodes with this commit @hzhou.

**Comment by hzhou** [comment]
The place that I set the environment is apparently too late. Apparently `proxy` only checks environment bag after all its other business. I'll find a earlier initialization point to make that patch -- this time I'll double check on JLSE to make sure.

**Comment by hzhou** [comment]
I did `MPL_putenv(str)`, thinking that `str` is part of `argv`, which should be there for the entire lifetime. Well, it is not. It was a copy and gets freed after parsing. So I should do `MPL_putenv(MPL_strdup(str))`, which fixes it:
```
[skylake10 ~]$ HYDRA_TOPO_DEBUG=1 mpiexec -n 4 --bind-to hwthread date
process 0 binding: 1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
process 1 binding: 0000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000
process 3 binding: 0000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000
process 2 binding: 0100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
Fri Nov 30 02:29:57 UTC 2018
Fri Nov 30 02:29:57 UTC 2018
Fri Nov 30 02:29:57 UTC 2018
Fri Nov 30 02:29:57 UTC 2018
``` 
@raffenet It is a small fix that I don't feel it worth the PR process. Can we do a direct commit to the master?

**Comment by raffenet** [comment]
This sounds like a reasonable fix, but we'll now have to free those strings eventually, right?

**Comment by jedbrown** [comment]
I seem to be encountering this issue on two different generic Linux x86-64 machines using 3.4a2 and 3.3. The variable `HYDRA_TOPO_DEBUG=1` propagates to the ranks, but nothing is printed.

**Comment by raffenet** [comment]
@jedbrown just double checking you are actually setting a binding with `--bind-to=<foo>`? I'm looking at the code and it never checks for debug in the default case.

**Comment by jedbrown** [comment]
For example:
```
$ HYDRA_TOPO_DEBUG=1 mpiexec.hydra -n 2 --bind-to hwthread sh -c 'echo $HYDRA_TOPO_DEBUG'
1
1
```

**Comment by raffenet** [comment]
OK, let me see if I can reproduce.

**Comment by raffenet** [comment]
Can reproduce with CentOS 7. One solution would be to move all the envvar processing in the proxy up to `mpiexec` and convert to proxy launch arguments. I'll try and work up a patch for this.

**Comment by hzhou** [comment]
@raffenet Last time we were hung up on this:
>> So I should do MPL_putenv(MPL_strdup(str))...
>  This sounds like a reasonable fix, but we'll now have to free those strings eventually, right?

Anyway, all the envvar has been passed to proxy via `--global-inherited-env #count "A=.." "B=.." ...`.  and ...
> move all the envvar processing in the proxy up to mpiexec and convert to proxy launch arguments
will just add another commandline syntax/protocol between `mpiexec` and `proxy`, and you still need add code in the proxy to parse that commandline. So instead of doing this, why don't we directly add that code in the proxy to directly parse `--global-inherited-env`?

**Comment by hzhou** [comment]
I guess what I was suggesting is in the place that I did `MPL_putenv(str)`, we set a global debug variable instead, and then where we check `HYDRA_TOPO_DEBUG` using `getenv`, we can directly check that debug variable.

**Comment by raffenet** [comment]
> I guess what I was suggesting is in the place that I did `MPL_putenv(str)`, we set a global debug variable instead, and then where we check `HYDRA_TOPO_DEBUG` using `getenv`, we can directly check that debug variable.

That could work, but I think it's cleaner to capture this information in `mpiexec` and forward it to proxies as explicit arguments as I propose in #4604.
